name: Update Docker Development Docker Images

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build_push_dev_docker_images:
    name: Build and Push Docker Development Images
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup .npmrc for repository
        run: |
            echo -e "@tiptap-pro:registry=https://registry.tiptap.dev/\n//registry.tiptap.dev/:_authToken=${{ secrets.TIPTAP_TOKEN }}" > .npmrc

      - name: Build and Push Frontend to Docker Container Registry
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./apps/app/Dockerfile.web
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-frontend:develop
          push: true
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.api
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-backend:develop
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Plane-Deploy to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./apps/space/Dockerfile.space
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-deploy:develop
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Plane-Proxy to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-proxy:develop
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
